server:
  port: 5000

clients:
  product-api:
    base-url: http://localhost:3001
    timeout: 1000
    retry: 1
    endpoints:
      product: /product/{productId}
      similar-ids: /product/{productId}/similarids